// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package v1

import (
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/GoogleChrome/webstatus.dev/lib/gen/openapi/backend"
	"github.com/GoogleChrome/webstatus.dev/lib/workertypes"
)

// Change represents a value transition from Old to New.
type Change[T any] struct {
	From T `json:"from"`
	To   T `json:"to"`
}

// ChangeReason describes why a feature was added or removed.
type ChangeReason string

const (
	ReasonNewMatch  ChangeReason = "new_match"
	ReasonUnmatched ChangeReason = "unmatched"
	ReasonDeleted   ChangeReason = "deleted"
)

// --- Diff Types (Output of Ingestion / Input of Delivery) ---
// These types represent the EVENT generated by comparing two States.
// We do NOT use OptionallySet here because Diffs are immutable records created
// at a point in time. If a field is empty in a Diff, it simply means no change occurred
// or the data wasn't available, which is handled by pointers or zero values.

// LatestFeatureDiff is an alias for the latest version of the FeatureDiff struct.
// When a new version is created (e.g. FeatureDiffV2), this alias should be updated to point to the new version.
type LatestFeatureDiff = FeatureDiffV1

// LatestFeatureDiffSnapshot is an alias for the latest version of the FeatureDiffSnapshot struct.
type LatestFeatureDiffSnapshot = FeatureDiffSnapshotV1

// LatestFeatureDiffVersion is a constant for the latest version of the FeatureListDiff schema.
const LatestFeatureDiffVersion = V1FeatureListDiff

// KindFeatureListDiff identifies a delta report of feature changes.
const KindFeatureListDiff = "FeatureListDiff"

// V1FeatureListDiff identifies version v1 of the FeatureListDiff schema.
const V1FeatureListDiff = "v1"

type FeatureDiffSnapshotV1 struct {
	Metadata DiffMetadataV1 `json:"metadata"`
	Data     FeatureDiffV1  `json:"data"`
}

func (d FeatureDiffSnapshotV1) Kind() string    { return "FeatureListDiff" }
func (d FeatureDiffSnapshotV1) Version() string { return V1FeatureListDiff }

type DiffMetadataV1 struct {
	GeneratedAt     time.Time `json:"generatedAt"`
	EventID         string    `json:"eventId"`
	SearchID        string    `json:"searchId"`
	ID              string    `json:"id"`
	PreviousStateID string    `json:"previousStateId,omitempty"`
	NewStateID      string    `json:"newStateId"`
}

type FeatureDiffV1 struct {
	QueryChanged bool              `json:"queryChanged,omitempty"`
	Added        []FeatureAdded    `json:"added,omitempty"`
	Removed      []FeatureRemoved  `json:"removed,omitempty"`
	Modified     []FeatureModified `json:"modified,omitempty"`
	Moves        []FeatureMoved    `json:"moves,omitempty"`
	Splits       []FeatureSplit    `json:"splits,omitempty"`
}

// Sort orders all slices deterministically by Name (primary) and ID (secondary).
// This ensures stable JSON output and organized UI/Email lists.
func (d *FeatureDiffV1) Sort() {
	sort.Slice(d.Added, func(i, j int) bool {
		if d.Added[i].Name != d.Added[j].Name {
			return d.Added[i].Name < d.Added[j].Name
		}

		return d.Added[i].ID < d.Added[j].ID
	})
	sort.Slice(d.Removed, func(i, j int) bool {
		if d.Removed[i].Name != d.Removed[j].Name {
			return d.Removed[i].Name < d.Removed[j].Name
		}

		return d.Removed[i].ID < d.Removed[j].ID
	})
	sort.Slice(d.Modified, func(i, j int) bool {
		if d.Modified[i].Name != d.Modified[j].Name {
			return d.Modified[i].Name < d.Modified[j].Name
		}

		return d.Modified[i].ID < d.Modified[j].ID
	})
	sort.Slice(d.Moves, func(i, j int) bool {
		if d.Moves[i].FromName != d.Moves[j].FromName {
			return d.Moves[i].FromName < d.Moves[j].FromName
		}

		return d.Moves[i].FromID < d.Moves[j].FromID
	})
	sort.Slice(d.Splits, func(i, j int) bool {
		if d.Splits[i].FromName != d.Splits[j].FromName {
			return d.Splits[i].FromName < d.Splits[j].FromName
		}

		return d.Splits[i].FromID < d.Splits[j].FromID
	})

	// Also sort the targets within a Split
	for k := range d.Splits {
		to := d.Splits[k].To
		sort.Slice(to, func(i, j int) bool {
			if to[i].Name != to[j].Name {
				return to[i].Name < to[j].Name
			}

			return to[i].ID < to[j].ID
		})
	}
}

// Representation of https://github.com/web-platform-dx/web-features-mappings/blob/main/mappings/mdn-docs.json
// Mapping data can change structure so mark all of these as pointers.
type MdnDoc struct {
	URL   *string `json:"url,omitzero"`
	Title *string `json:"title,omitzero"`
	Slug  *string `json:"slug,omitzero"`
}

type Docs struct {
	MdnDocs []MdnDoc `json:"mdnDocs,omitzero"`
}

type FeatureAdded struct {
	ID     string       `json:"id"`
	Name   string       `json:"name"`
	Reason ChangeReason `json:"reason"`
	Docs   *Docs        `json:"docs,omitempty"`
}

type FeatureRemoved struct {
	ID     string       `json:"id"`
	Name   string       `json:"name"`
	Reason ChangeReason `json:"reason"`
}

type FeatureMoved struct {
	FromID   string `json:"fromId"`
	ToID     string `json:"toId"`
	FromName string `json:"fromName"`
	ToName   string `json:"toName"`
}

type FeatureSplit struct {
	FromID   string         `json:"fromId"`
	FromName string         `json:"fromName"`
	To       []FeatureAdded `json:"to"`
}

type FeatureModified struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Docs *Docs  `json:"docs,omitempty"`

	NameChange     *Change[string]                                     `json:"nameChange,omitempty"`
	BaselineChange *Change[BaselineState]                              `json:"baselineChange,omitempty"`
	BrowserChanges map[backend.SupportedBrowsers]*Change[BrowserState] `json:"browserChanges,omitempty"`
	DocsChange     *Change[Docs]                                       `json:"docsChange,omitempty"`
}

// BrowserState captures the implementation details for a specific browser.
type BrowserState struct {
	Status  backend.BrowserImplementationStatus `json:"status,omitzero"`
	Date    *time.Time                          `json:"date,omitzero"`
	Version *string                             `json:"version,omitzero"`
}

// BaselineState captures the full status context for a feature's baseline.
type BaselineState struct {
	Status   backend.BaselineInfoStatus `json:"status,omitzero"`
	LowDate  *time.Time                 `json:"lowDate,omitzero"`
	HighDate *time.Time                 `json:"highDate,omitzero"`
}

func (d FeatureDiffV1) Summarize() workertypes.EventSummary {
	var s workertypes.EventSummary
	s.SchemaVersion = workertypes.VersionEventSummaryV1
	var parts []string

	if d.QueryChanged {
		parts = append(parts, "Search criteria updated")
		s.Categories.QueryChanged = 1
	}

	if len(d.Added) > 0 {
		parts = append(parts, fmt.Sprintf("%d features added", len(d.Added)))
		s.Categories.Added = len(d.Added)
	}
	if len(d.Removed) > 0 {
		parts = append(parts, fmt.Sprintf("%d features removed", len(d.Removed)))
		s.Categories.Removed = len(d.Removed)
	}
	if len(d.Moves) > 0 {
		parts = append(parts, fmt.Sprintf("%d features moved/renamed", len(d.Moves)))
		s.Categories.Moved = len(d.Moves)
	}
	if len(d.Splits) > 0 {
		parts = append(parts, fmt.Sprintf("%d features split", len(d.Splits)))
		s.Categories.Split = len(d.Splits)
	}

	if len(d.Modified) > 0 {
		parts = append(parts, fmt.Sprintf("%d features updated", len(d.Modified)))
		s.Categories.Updated = len(d.Modified)

		for _, m := range d.Modified {
			if len(m.BrowserChanges) > 0 {
				s.Categories.UpdatedImpl++
			}
			if m.NameChange != nil {
				s.Categories.UpdatedRename++
			}
			if m.BaselineChange != nil {
				s.Categories.UpdatedBaseline++
			}
		}
	}

	if len(parts) == 0 {
		s.Text = "No changes detected"
	} else {
		s.Text = strings.Join(parts, ", ")
	}

	return s
}

func (d FeatureDiffV1) HasChanges() bool {
	return d.QueryChanged || len(d.Added) > 0 || len(d.Removed) > 0 ||
		len(d.Modified) > 0 || len(d.Moves) > 0 || len(d.Splits) > 0
}
