# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '2'
linters:
  default: none
  enable:
    - containedctx
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - gochecknoglobals
    - gocognit
    - goconst
    - gocyclo
    - godot
    - goheader
    - gomoddirectives
    - gosec
    - govet
    - importas
    - ineffassign
    - ireturn
    - lll
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - prealloc
    - revive
    - staticcheck
    - unparam
    - unused
    - usestdlibvars
  settings:
    gomoddirectives:
      replace-local: true
    dupl:
      # The default is 150
      threshold: 175
    exhaustive:
      check:
        - switch
        - map
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - lib/gen
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - lib/gen
      - third_party$
      - builtin$
      - examples$
