# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# DSN (Database Source Name) to connect database
dsn: spanner://local/local/local

# Path to generate document
docPath: docs/schema

exclude:
  - SchemaMigrations
er:
  hideDef: true
# The tool only gets some of the relations automatically.
# Use this section to fill in the rest.
# TODO. Reach back out to tool author to add more support for spanner.
relations:
  - table: WPTRunFeatureMetrics
    columns:
      - FeatureID
    parentTable: WebFeatures
    parentColumns:
      - FeatureID
  - table: BrowserFeatureAvailabilities
    columns:
      - FeatureID
    parentTable: WebFeatures
    parentColumns:
      - FeatureID
  - table: BrowserFeatureAvailabilities
    columns:
      - BrowserName
      - BrowserVersion
    parentTable: BrowserReleases
    parentColumns:
      - BrowserName
      - BrowserVersion
  - table: FeatureBaselineStatus
    columns:
      - FeatureID
    parentTable: WebFeatures
    parentColumns:
      - FeatureID
