# Copyright 2023 Google LLC

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     https://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: frontend
  annotations:
    # This disables debug mode since this is running an NGINX container.
    debug.cloud.google.com/config: '{}'
spec:
  containers:
    - name: frontend
      image: frontend
      imagePullPolicy: Never # Need this for pushing directly into minikube
      ports:
        - containerPort: 5555
          name: http-frontend
      env:
        - name: API_URL
          value: http://localhost:8080
        - name: GOOGLE_ANALYTICS_ID
          value: G-EPZE5TL134
        - name: FIREBASE_AUTH_EMULATOR_URL
          value: http://localhost:9099
        - name: FIREBASE_APP_API_KEY
          value: local
        - name: FIREBASE_APP_AUTH_DOMAIN
          value: local
        - name: K_REVISION
          value: local
      resources:
        limits:
          cpu: 250m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 64Mi
