apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: redis-config
profiles:
  - name: local
    build:
      artifacts:
        - image: redis
          context: .
      local: {}
    manifests:
      rawYaml:
        - manifests/*
    deploy:
      kubectl: {}
