#!/bin/bash
set -e

# Get the directory of the script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export DEPLOY_ENV="staging"
export GCP_PROJECT="web-compass-staging"
export SPANNER_PROJECT="webstatus-dev-internal-staging"
export WEBSITE_URL="https://website-webstatus-dev.corp.goog/"
export API_URL="https://api-webstatus-dev.corp.goog/v1/features"

"$DIR/deploy-env"
