// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package differ

import (
	"context"
	"errors"
	"time"

	"github.com/GoogleChrome/webstatus.dev/lib/backendtypes"
	"github.com/GoogleChrome/webstatus.dev/lib/gen/openapi/backend"
	"github.com/GoogleChrome/webstatus.dev/lib/workertypes"
	"github.com/GoogleChrome/webstatus.dev/lib/workertypes/comparables"
)

var (
	ErrNoChangesDetected = errors.New("no changes detected")
	ErrTransient         = errors.New("transient failure")
	ErrFatal             = errors.New("fatal error")
)

// FeatureFetcher abstracts the external API.
type FeatureFetcher interface {
	FetchFeatures(ctx context.Context, query string) ([]backend.Feature, error)
	GetFeature(ctx context.Context, featureID string) (*backendtypes.GetFeatureResult, error)
}

type StateCompareWorkflow[D any] interface {
	CalculateDiff(oldSnapshot, newSnapshot map[string]comparables.Feature)
	ReconcileHistory(ctx context.Context) error
	HasRemovedFeatures() bool
	HasChanges() bool
	HasDataChanges() bool
	SetQueryChanged(bool)
	GetDiff() *D
	GenerateJSONSummary() ([]byte, error)
}

type FeatureDiffer[D any] struct {
	client         FeatureFetcher
	stateAdapter   StateAdapter
	diffSerializer DiffSerializer[D]
	workflow       StateCompareWorkflow[D]
	idGenerator    idGenerator
	timeNow        func() time.Time
}

// StateAdapter defines the contract for loading and serializing the versioned state snapshot.
type StateAdapter interface {
	// Load deserializes the state blob bytes, handling any necessary migrations.
	Load(bytes []byte) (
		snapshot map[string]comparables.Feature,
		id string,
		signature string,
		isEmpty bool,
		err error,
	)

	// Serialize creates a new state blob from the internal feature snapshot.
	Serialize(id, searchID, eventID, query string, timestamp time.Time,
		snapshot map[string]comparables.Feature) ([]byte, error)
}

// DiffSerializer defines the contract for serializing the final diff result.
// D is the concrete diff type produced by the workflow (e.g., v1.FeatureDiff).
type DiffSerializer[D any] interface {
	Serialize(id, searchID, eventID, newStateID, previousStateID string, diff *D, timestamp time.Time) ([]byte, error)
}

// DiffMetadata provides the necessary context for the DiffSerializer to build the blob envelope.
type DiffMetadata struct {
	ID              string
	EventID         string
	SearchID        string
	NewStateID      string
	PreviousStateID string
}

func NewFeatureDiffer[D any](client FeatureFetcher, workflow StateCompareWorkflow[D], stateAdapter StateAdapter,
	diffSerializer DiffSerializer[D]) *FeatureDiffer[D] {
	return &FeatureDiffer[D]{
		client:         client,
		workflow:       workflow,
		stateAdapter:   stateAdapter,
		diffSerializer: diffSerializer,
		idGenerator:    &defaultIDGenerator{},
		timeNow:        time.Now,
	}
}

// BlobArtifact represents a payload that needs to be persisted to object storage (GCS).
type BlobArtifact struct {
	ID    string
	Bytes []byte
}

// DiffResult encapsulates the artifacts and metadata generated by a successful diff operation.
//
// If no changes are detected, the Differ should return nil, not an empty DiffResult.
type DiffResult struct {
	// Artifacts to be stored
	State BlobArtifact
	Diff  BlobArtifact

	// Metadata for the Event Bus / Database

	// Summary is the serialized JSON payload describing the changes (e.g. `{"added": 1, "removed": 0}`).
	// It is provided as bytes so the caller can pass it directly to storage without re-marshalling.
	Summary []byte

	// Reasons contains machine-readable tags explaining the event (e.g. "DATA_UPDATED", "QUERY_EDITED").
	Reasons []workertypes.Reason

	// Timestamp that the diff was generated
	GeneratedAt time.Time
}
