// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package v1

import (
	"time"

	"github.com/GoogleChrome/webstatus.dev/lib/workertypes"
)

// JobFrequency defines the frequency that triggered this batch refresh.
type JobFrequency string

const (
	FrequencyUnknown   JobFrequency = "UNKNOWN"
	FrequencyImmediate JobFrequency = "IMMEDIATE"
	FrequencyWeekly    JobFrequency = "WEEKLY"
	FrequencyMonthly   JobFrequency = "MONTHLY"
)

func (f JobFrequency) ToWorkerTypeJobFrequency() workertypes.JobFrequency {
	switch f {
	case FrequencyImmediate:
		return workertypes.FrequencyImmediate
	case FrequencyWeekly:
		return workertypes.FrequencyWeekly
	case FrequencyMonthly:
		return workertypes.FrequencyMonthly
	case FrequencyUnknown:
		return workertypes.FrequencyUnknown
	}

	return workertypes.FrequencyUnknown
}

// RefreshSearchCommand is the signal sent by the Fan-Out Worker to the Event Producer.
// One of these is published for EACH active search found in the database matching the batch frequency.
type RefreshSearchCommand struct {
	// SearchID is the target saved search to check.
	SearchID string `json:"search_id"`

	// Query is the current search filter (e.g. "browsers:chrome").
	Query string `json:"query"`

	// Frequency indicates which schedule triggered this refresh.
	Frequency JobFrequency `json:"frequency"`

	// Timestamp is when the batch process started (generated by the Fan-Out worker).
	// Useful for identifying lag (if the worker processes it 10m later).
	Timestamp time.Time `json:"timestamp"`
}

func (RefreshSearchCommand) Kind() string       { return "RefreshSearchCommand" }
func (RefreshSearchCommand) APIVersion() string { return "v1" }
